### ISSUE TITLE
Followed the readme step by step but got error with example data

### ISSUE THREAD

**Issue by Fang-Kevin** [deepomicslab/SpecHLA#43]
Hi,

I am trying to run "test_whole.sh" with example data "whole".
but it gives the following error at "phase_variants.py" step. 
I lack novoalign lic so the script use bowtie2 instead.

Hoping for your suggestion
Thank you,

Latest update: 
These error only occur on my Ubuntu 24.04 LTS of win11(64G RAM).
This pipeline run successfully on my HPC.

```
Mean depth {'HLA_A': 28, 'HLA_B': 21, 'HLA_C': 23, 'HLA_DPA1': 26, 'HLA_DPB1': 36, 'HLA_DQA1': 21, 'HLA_DQB1': 23, 'HLA_DRB1': 17}
Minimum Minor Allele Frequency is 0.05.
Num of hete small variant is 76 in HLA_A.
Segmentation fault
1 blocks after phasing.
Start link blocks with database...
No need to phase block.
phase block with spectral graph theory
Traceback (most recent call last):
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1893, in <module>
    update_seqlist = link_blocks()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1683, in link_blocks
    update_seqlist = block_phase(outdir,seq_list,snp_list,gene,gene_vcf,rephase_vcf,record_block_haps)
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 580, in block_phase
    phased_locus=seq[he]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I also tried exon example and it works on  some hla(HLA_DPA1_1      HLA_DPA1_2      HLA_DPB1_1      HLA_DPB1_2      HLA_DQA1_1      HLA_DQA1_2), but the others failed. 

It seems that only "Num of hete small variant is 0" can generate sequential result 

```
start realignment...

Attention: please ensure the platform can run gzip -l automatically, otherwise, it may not continue.
BAM and VCF are ready.
Mean depth {'HLA_A': 56, 'HLA_B': 37, 'HLA_C': 48, 'HLA_DPA1': 12, 'HLA_DPB1': 39, 'HLA_DQA1': 38, 'HLA_DQB1': 21, 'HLA_DRB1': 20}
Minimum Minor Allele Frequency is 0.1.
Num of hete small variant is 30 in HLA_A.
Segmentation fault
1 blocks after phasing.
Start link blocks with database...
Num of all possible haps is 1.
Traceback (most recent call last):
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1893, in <module>
    update_seqlist = link_blocks()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1666, in link_blocks
    update_seqlist = all_poss_block_link()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1605, in all_poss_block_link
    update_seqlist = block_phase(outdir,seq_list,snp_list,gene,gene_vcf,rephase_vcf,record_block_haps)
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 580, in block_phase
    phased_locus=seq[he]
IndexError: index 0 is out of bounds for axis 0 with size 0
Num of hete small variant is 26 in HLA_B.
Segmentation fault
1 blocks after phasing.
Start link blocks with database...
Num of all possible haps is 1.
Traceback (most recent call last):
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1893, in <module>
    update_seqlist = link_blocks()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1666, in link_blocks
    update_seqlist = all_poss_block_link()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1605, in all_poss_block_link
    update_seqlist = block_phase(outdir,seq_list,snp_list,gene,gene_vcf,rephase_vcf,record_block_haps)
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 580, in block_phase
    phased_locus=seq[he]
IndexError: index 0 is out of bounds for axis 0 with size 0
Num of hete small variant is 27 in HLA_C.
Segmentation fault
1 blocks after phasing.
Start link blocks with database...
Num of all possible haps is 1.
Traceback (most recent call last):
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1893, in <module>
    update_seqlist = link_blocks()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1666, in link_blocks
    update_seqlist = all_poss_block_link()
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 1605, in all_poss_block_link
    update_seqlist = block_phase(outdir,seq_list,snp_list,gene,gene_vcf,rephase_vcf,record_block_haps)
  File "/home/rorschach/SpecHLA/script/whole/../phase_variants.py", line 580, in block_phase
    phased_locus=seq[he]
IndexError: index 0 is out of bounds for axis 0 with size 0
Num of hete small variant is 0 in HLA_DPA1.
No heterozygous locus, no need to phase.
Phasing of HLA_DPA1 is done!


Num of hete small variant is 0 in HLA_DPB1.
No heterozygous locus, no need to phase.
Phasing of HLA_DPB1 is done!


Num of hete small variant is 0 in HLA_DQA1.
No heterozygous locus, no need to phase.
Phasing of HLA_DQA1 is done!
'
'(omit)
'
# version: IPD-IMGT/HLA 3.57.0
Sample  HLA_A_1 HLA_A_2 HLA_B_1 HLA_B_2 HLA_C_1 HLA_C_2 HLA_DPA1_1      HLA_DPA1_2      HLA_DPB1_1      HLA_DPB1_2      HLA_DQA1_1      HLA_DQA1_2      HLA_DQB1_1   HLA_DQB1_2      HLA_DRB1_1      HLA_DRB1_2
NA06985 -       -       -       -       -       -       DPA1*01:03:01:01        DPA1*01:03:01:01        DPB1*04:01:01:01        DPB1*04:01:01:01        DQA1*01:02:01:01     DQA1*01:02:01:01        -       -       -       -
```

**Comment by wshuai294** [comment]
Hello,
As the `Segmentation fault` in the phasing variants step, it seems the installation is unsuccessful on your Ubuntu 24.04 LTS of win11. Could you please also send me the installation log?
